version: '3'

services:
  test_api:
    build: .
    container_name: test-api
    environment:
      VIRTUAL_HOST: test.vllirette.com
      ASPNETCORE_ENVIRONMENT: Development
    networks:
      - nginxproxy
      - mongodb
    ports:
      - 8082:80

networks:
  nginxproxy:
    external:
      name: nginxproxy
  mongodb:
    external:
      name: mongodb
