version: '3'

services:
  nginx-proxy:
    container_name: nginx-proxy
    restart: always
    image: jwilder/nginx-proxy
    environment:
      DEFAULT_HOST: vllirette.com
    ports:
      - 80:80
    networks:
      - nginxproxy
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

networks:
  nginxproxy:
    external:
      name: nginxproxy
